name: Deploy Go App to Elastic Beanstalk

on:
  push:
    branches:
      - elastic-beanstalk-ec2

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build Go application
        run: |
          go mod download
          go build -o bin/application main.go

      - name: Archive application
        run: zip -r application.zip bin/

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: go-app 
          environment_name: go-app-env 
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: application.zip
          use_existing_version_if_available: true
